// Generated by Phaser Editor v1.2.1

/**
 * startScene.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function startScene(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	this.game.add.sprite(0, 0, 'uiAtlas', 'bg_top.png', this);

	this.game.add.sprite(0, 181, 'uiAtlas', 'game_board.png', this);

	this.game.add.sprite(0, 654, 'uiAtlas', 'bg_bottom.png', this);

	var UITimeGauge_body_png = this.game.add.sprite(56, 703, 'uiAtlas', 'UITimeGauge_body.png', this);
	UITimeGauge_body_png.scale.setTo(0.8399999712077841, 1.0626088119527406);

	var UITimeGauge_header_png = this.game.add.sprite(47, 703, 'uiAtlas', 'UITimeGauge_header.png', this);
	UITimeGauge_header_png.scale.setTo(1.0, 1.06);

	var UITimeGauge_tail_png = this.game.add.sprite(433, 703, 'uiAtlas', 'UITimeGauge_tail.png', this);
	UITimeGauge_tail_png.scale.setTo(1.0, 1.06);

	var UICombo_png = this.game.add.sprite(256, 88, 'uiAtlas', 'combo0011.png', this);


	/* --- post-init-begin --- */

	// you can insert code here
	this.fImg_time_gauge_body = UITimeGauge_body_png;
	this.fImg_time_gauge_tail = UITimeGauge_tail_png;
	this.fImg_time_gauge_head = UITimeGauge_header_png;
	this.fImg_Combo = UICombo_png;
	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var startScene_proto = Object.create(Phaser.Group.prototype);
startScene.prototype = startScene_proto;
startScene.prototype.constructor = Phaser.Group;

/* --- end generated code --- */

// you can insert code here

